apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: nkg9mzblg-go 
  janus-idp.io/tekton: nkg9mzblg-go
  backstage.io/kubernetes-id: nkg9mzblg-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: nkg9mzblg-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  